workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - admin
     ios_signing:
        distribution_type: app_store
        bundle_identifier: noon.team.mn
        
     scripts:
         - name: Set up code signing settings on Xcode project
         script: xcode-project use-profiles  
        