workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - admin 
     ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: noon.team.mn 