workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
    
     vars:
      BUNDLE_ID: "noon.team.mn"
      XCODE_WORKSPACE: "WKWebViewLocalAssetsObjC.xcworkspace" # <-- Name of your Xcode workspace
      XCODE_SCHEME: "WKWebViewLocalAssetsObjC" # <-- Name of your Xcode scheme
    
    
      groups:
        - admin
     ios_signing:
        distribution_type: app_store
        bundle_identifier: noon.team.mn
        
     scripts:
         - name: Set up code signing settings on Xcode project
         script: xcode-project use-profiles  
         
        - name: Build ipa for distribution
        script: | 
        xcode-project build-ipa \
        --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
        --scheme "$XCODE_SCHEME"
     artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        