 workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: CodemagicSign
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: noon.team.mn
    scripts:
     - script: keychain initilize
     - script: keychain add-certificates
	 
     - script: xcode-project use-profiles
     
   
    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - jomart1985@mail.com
        notify:
          success: true
          failure: false
    
  
  
  
  
  
  
  